// ===========================================================
// lib/db/lr.ts
// Reference DB HELPER for Lorry Receipt queries
// ===========================================================
//
// This is Layer 3 in the 3-layer architecture.
//
// Rules:
// - Pure typed Supabase queries — no business logic.
// - Receives a typed Supabase client — never creates its own.
// - Always select specific columns — never use .select('*').
// - Returns raw Supabase response ({ data, error, count }).
// - Does NOT validate authorization — that's the service layer's job.
// - Naming: getVerb / insertVerb / updateVerb / deleteVerb

import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// --------------- Types ---------------

interface PaginationParams {
  page?: number;
  pageSize?: number;
}

interface LRFilters {
  status?: string;
  fromHubId?: string;
  toHubId?: string;
  dateFrom?: string;
  dateTo?: string;
  search?: string; // searches lr_number, consignor_name, consignee_name
}

type LRInsertRow = Database['public']['Tables']['lorry_receipts']['Insert'];

// --------------- Queries ---------------

/**
 * Get a single LR by ID.
 * Includes hub names via join — avoids N+1 lookups.
 */
export async function getLRById(
  supabase: SupabaseClient<Database>,
  id: string
) {
  return supabase
    .from('lorry_receipts')
    .select(`
      id, lr_number, status, booking_date, source,
      freight_amount, payment_mode, goods_description,
      quantity, weight_kg, num_packages,
      consignor_name, consignor_phone, consignor_gstin,
      consignee_name, consignee_phone, consignee_gstin,
      expected_delivery_date, trip_id, tenant_id,
      from_hub_id, to_hub_id, created_by,
      from_hub:hubs!from_hub_id(id, name, hub_code),
      to_hub:hubs!to_hub_id(id, name, hub_code)
    `)
    .eq('id', id)
    .single();
}

/**
 * List LRs with filtering, search, and pagination.
 * Default page size: 25 (offset-based).
 *
 * ✅ Uses { count: 'exact' } for pagination metadata.
 * ✅ Selects only needed columns — never select('*').
 * ✅ Builds query dynamically based on provided filters.
 */
export async function getLRList(
  supabase: SupabaseClient<Database>,
  filters: LRFilters = {},
  { page = 0, pageSize = 25 }: PaginationParams = {}
) {
  let query = supabase
    .from('lorry_receipts')
    .select(
      `id, lr_number, status, booking_date, freight_amount, payment_mode,
       consignor_name, consignee_name,
       from_hub:hubs!from_hub_id(name, hub_code),
       to_hub:hubs!to_hub_id(name, hub_code)`,
      { count: 'exact' }
    )
    .order('created_at', { ascending: false });

  // Apply filters dynamically
  if (filters.status) {
    query = query.eq('status', filters.status);
  }
  if (filters.fromHubId) {
    query = query.eq('from_hub_id', filters.fromHubId);
  }
  if (filters.toHubId) {
    query = query.eq('to_hub_id', filters.toHubId);
  }
  if (filters.dateFrom) {
    query = query.gte('booking_date', filters.dateFrom);
  }
  if (filters.dateTo) {
    query = query.lte('booking_date', filters.dateTo);
  }
  if (filters.search) {
    // Supabase .or() for multi-column search
    query = query.or(
      `lr_number.ilike.%${filters.search}%,` +
      `consignor_name.ilike.%${filters.search}%,` +
      `consignee_name.ilike.%${filters.search}%`
    );
  }

  // Apply pagination (offset-based)
  query = query.range(page * pageSize, (page + 1) * pageSize - 1);

  return query;
}

/**
 * Get LRs by hub (for Hub Manager dashboard).
 * Only returns LRs where from_hub_id matches.
 */
export async function getLRsByHub(
  supabase: SupabaseClient<Database>,
  hubId: string,
  { page = 0, pageSize = 25 }: PaginationParams = {}
) {
  return supabase
    .from('lorry_receipts')
    .select(
      'id, lr_number, status, booking_date, freight_amount, consignor_name, consignee_name',
      { count: 'exact' }
    )
    .eq('from_hub_id', hubId)
    .order('created_at', { ascending: false })
    .range(page * pageSize, (page + 1) * pageSize - 1);
}

// --------------- Mutations ---------------

/**
 * Insert a new LR. Returns the created row with id and lr_number.
 * lr_number is auto-generated by the database trigger.
 */
export async function insertLR(
  supabase: SupabaseClient<Database>,
  row: LRInsertRow
) {
  return supabase
    .from('lorry_receipts')
    .insert(row)
    .select('id, lr_number')
    .single();
}

/**
 * Update LR status. Only updates the status column.
 */
export async function updateLRStatus(
  supabase: SupabaseClient<Database>,
  id: string,
  status: string
) {
  return supabase
    .from('lorry_receipts')
    .update({ status })
    .eq('id', id);
}

/**
 * Get LR counts grouped by status (for dashboard widgets).
 * Uses Supabase RPC for efficient server-side aggregation.
 *
 * Note: This requires a Postgres function:
 *   CREATE FUNCTION get_lr_status_counts(p_tenant_id UUID)
 *   RETURNS TABLE(status TEXT, count BIGINT)
 */
export async function getLRStatusCounts(
  supabase: SupabaseClient<Database>,
  tenantId: string
) {
  return supabase.rpc('get_lr_status_counts', { p_tenant_id: tenantId });
}
