-- =============================================================================
-- Migration 7: lorry_receipts + hub-scoped RLS + auto-numbering trigger
-- =============================================================================

CREATE TABLE public.lorry_receipts (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lr_number               text UNIQUE, -- Auto-generated by trigger
  booking_date            date NOT NULL DEFAULT CURRENT_DATE,
  source                  text NOT NULL DEFAULT 'HUB_DIRECT'
                          CHECK (source IN ('HUB_DIRECT', 'CUSTOMER_REQUEST')),
  -- Route
  from_hub_id             uuid NOT NULL REFERENCES public.hubs(id) ON DELETE RESTRICT,
  to_hub_id               uuid NOT NULL REFERENCES public.hubs(id) ON DELETE RESTRICT,
  trip_id                 uuid REFERENCES public.trips(id) ON DELETE SET NULL,
  -- Consignor (sender)
  consignor_name          text NOT NULL,
  consignor_phone         text NOT NULL,
  consignor_gstin         text,
  -- Consignee (receiver)
  consignee_name          text NOT NULL,
  consignee_phone         text NOT NULL,
  consignee_gstin         text,
  -- Goods
  goods_description       text NOT NULL,
  quantity                integer NOT NULL DEFAULT 1,
  weight_kg               decimal(10, 2),
  num_packages            integer NOT NULL DEFAULT 1,
  -- Financials (stored in paise)
  freight_amount          bigint NOT NULL DEFAULT 0, -- Amount in paise (1 INR = 100 paise)
  payment_mode            text NOT NULL DEFAULT 'PAID'
                          CHECK (payment_mode IN ('PAID', 'TO_PAY', 'TBB')),
  -- Dates
  expected_delivery_date  date,
  -- Status
  status                  text NOT NULL DEFAULT 'BOOKING_PENDING'
                          CHECK (status IN (
                            'BOOKING_PENDING', 'BOOKED', 'PICKED_UP', 'IN_TRANSIT',
                            'ARRIVED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED'
                          )),
  -- Metadata
  booking_request_id      uuid REFERENCES public.booking_requests(id) ON DELETE SET NULL,
  tenant_id               uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_by              uuid REFERENCES public.users(id) ON DELETE SET NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lr_different_hubs CHECK (from_hub_id != to_hub_id)
);

-- Enable RLS
ALTER TABLE public.lorry_receipts ENABLE ROW LEVEL SECURITY;

-- All tenant members can SELECT all LRs in their tenant
-- (Hub Managers can view LRs from all hubs for reference, per CONTEXT.md §12)
CREATE POLICY "tenant_select_lr" ON public.lorry_receipts
  FOR SELECT USING (tenant_id = current_tenant_id());

-- Hub-scoped INSERT: Fleet owners can create anywhere;
-- Hub managers can only create LRs at their assigned hubs
CREATE POLICY "hub_scoped_insert_lr" ON public.lorry_receipts
  FOR INSERT WITH CHECK (
    tenant_id = current_tenant_id()
    AND (
      current_user_role() = 'fleet_owner'
      OR (
        current_user_role() = 'hub_manager'
        AND from_hub_id = ANY(current_user_hub_ids())
      )
    )
  );

-- Hub-scoped UPDATE: Fleet owners can update any LR;
-- Hub managers can only update LRs at their assigned hubs
CREATE POLICY "hub_scoped_update_lr" ON public.lorry_receipts
  FOR UPDATE USING (
    tenant_id = current_tenant_id()
    AND (
      current_user_role() = 'fleet_owner'
      OR (
        current_user_role() = 'hub_manager'
        AND (
          from_hub_id = ANY(current_user_hub_ids())
          OR to_hub_id = ANY(current_user_hub_ids())
        )
      )
    )
  );

-- Only fleet_owner can delete LRs (soft-delete preferred in practice)
CREATE POLICY "fleet_owner_delete_lr" ON public.lorry_receipts
  FOR DELETE USING (
    tenant_id = current_tenant_id()
    AND current_user_role() = 'fleet_owner'
  );

-- Indexes
CREATE INDEX idx_lr_tenant ON public.lorry_receipts(tenant_id);
CREATE INDEX idx_lr_status ON public.lorry_receipts(tenant_id, status);
CREATE INDEX idx_lr_from_hub ON public.lorry_receipts(from_hub_id);
CREATE INDEX idx_lr_to_hub ON public.lorry_receipts(to_hub_id);
CREATE INDEX idx_lr_trip ON public.lorry_receipts(trip_id);
CREATE INDEX idx_lr_booking_date ON public.lorry_receipts(tenant_id, booking_date DESC);
CREATE INDEX idx_lr_number ON public.lorry_receipts(lr_number);
CREATE INDEX idx_lr_consignor_phone ON public.lorry_receipts(consignor_phone);
CREATE INDEX idx_lr_consignee_phone ON public.lorry_receipts(consignee_phone);

-- =============================================================================
-- Auto-numbering trigger: generate lr_number on INSERT
-- =============================================================================
CREATE OR REPLACE FUNCTION public.set_lr_number()
RETURNS trigger AS $$
BEGIN
  IF NEW.lr_number IS NULL THEN
    NEW.lr_number := public.generate_lr_number(NEW.from_hub_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_set_lr_number
  BEFORE INSERT ON public.lorry_receipts
  FOR EACH ROW EXECUTE FUNCTION public.set_lr_number();

-- =============================================================================
-- Add FK from booking_requests.lr_id to lorry_receipts
-- =============================================================================
ALTER TABLE public.booking_requests
  ADD CONSTRAINT fk_booking_request_lr
  FOREIGN KEY (lr_id) REFERENCES public.lorry_receipts(id) ON DELETE SET NULL;
